name: Deploy app to ghpages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Installing bun
        uses: oven-sh/setup-bun@v1

      - run: bun install
      - run: bun run build
      - name: Deploy to gh-pages
        run: |
          mv dist/* ./
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git checkout -B gh-pages
          git add .
          git commit -m "Deploy to gh-pages"
          git push -f origin gh-pages

