name: Deploy app to ghpages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Installing bun
        uses: oven-sh/setup-bun@v1

      - run: bun install
      - run: bun run build
      - run: git checkout gh-pages
      - run: git add . && git commit -m "gh-pages deploy"

